### ISSUE TITLE
Sticky Navigation

### ISSUE THREAD

**Issue by httpJunkie** [MetaMask/mm-docs-v2#109]
The old docs have a sticky Navigation. Ensuring the access to the navigation is always available when scrolling.

I've not seen this in the docs v2 preview.

Example:
![Screenshot_20230407-090813](https://user-images.githubusercontent.com/4899480/230614323-5dc5f199-5e29-428e-9e81-01bfc66c5079.png)

**Comment by alexandratran** [comment]
I enabled the sticky nav in https://github.com/MetaMask/mm-docs-v2/pull/108, which is currently waiting for review.
