### ISSUE TITLE
Incorporate a search function into the docs

### ISSUE THREAD

**Issue by vandan** [MetaMask/mm-docs-v2#24]
In order to achieve parity with the legacy docs, we should incorporate a search function. The search functionality should be similar in behavior to what is currently possible, including:

* Keyword search
* [Autocomplete](https://www.algolia.com/blog/ux/what-are-predictive-search-and-autocomplete/) search results (results displayed as you type)

<img width="528" alt="Screenshot 2023-02-06 at 3 35 09 PM" src="https://user-images.githubusercontent.com/1643618/217111173-16b0d1a6-3498-4459-9eda-580273e5f74d.png">

**Comment by vandan** [comment]
@shanejonas @BelfordZ any thoughts on Algolia? Seems reasonable to me that we would stick with it because it sounds like Algolia is free for open source projects.
Still would need to follow the steps listed here to officially register ourselves though: https://docusaurus.io/docs/search

**Comment by BboyAkers** [comment]
I can look into this! 🙂 That's if no one is working on it already.

**Comment by BboyAkers** [comment]
Here's a PR! Not sure what the `API Key` , `appId` , `indexName`, and `externalUrlRegex`  info is but this'll work once you add those and then Algolia will be able to crawl the site. 🙂 

https://github.com/MetaMask/mm-docs-v2/pull/57

**Comment by vandan** [comment]
Great. Thanks @BboyAkers for getting us started with adding Search back in. We're hoping to make a big push to get all these little items addressed over the coming weeks.
We'll add the parameters once we fill out the Algolia form and get their approval.
