### ISSUE TITLE
Enumerate all redirects from the legacy docs URLs and the associated destination paths under the new docs

### ISSUE THREAD

**Issue by vandan** [MetaMask/mm-docs-v2#35]
@vandan and @alexandratran to document the set of redirects we should have in place in order to launch the new docs (replace legacy docs)

**Comment by alexandratran** [comment]
[Here](https://docs.google.com/spreadsheets/d/1-6NcE1L3y2OBMTgCLs3_Fdk9UCdwvsCyw2rx7nE0m-w/edit?usp=sharing) is a list of redirects from each page in the legacy site. I've just linked to the corresponding page in the staging site – let me know if we need anything else for clarity.
