### ISSUE TITLE
Determine what to do with legacy tutorials

### ISSUE THREAD

**Issue by vandan** [MetaMask/mm-docs-v2#53]
The legacy MetaMask [Wallet API tutorial](https://docs.metamask.io/guide/create-dapp.html#project-setup) is outdated (not working according to instructions). Currently, in the new docs, there are just [placeholder references](https://metamask.github.io/mm-docs-v2/staging/wallet/tutorials/create-simple-dapp).
Some possibilities for what we can do in the Public Launch:

1. Remove API & SDK tutorials from the technical documentation
2. Resolve issues in the respective tutorials
3. Create new & improved tutorials

**Comment by BboyAkers** [comment]
@alexandratran ya'll can totally scrap the "Create a Simple Dapp" tutorial if you'd like! 🙂 I'd be happy to help on a new one to be honest!

**Comment by alexandratran** [comment]
The placeholders are removed in #59 and a new tutorial will be created as per #4.
