### ISSUE TITLE
Document snaps tutorials

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/mm-docs-v2#6]
The [legacy snaps getting started tutorial](https://docs.metamask.io/guide/snaps.html#getting-started) works, but it doesn't walk the user through the process of creating or significantly customizing a snap.

We should have such a tutorial, that is end-to-end and beginner oriented, walking the user through creating a snap from scratch for a common use case. This tutorial should explain each part of the code.

Perhaps we just need to migrate and edit the following existing tutorials:
https://github.com/Montoya/gas-fee-snap#montoyagas-fee-snap
https://github.com/Montoya/address-book-snap-tutorial#montoyaaddress-book-snap-tutorial
https://archive.devcon.org/archive/watch/6/getting-started-with-metamask-snaps/?tab=YouTube
https://hackmd.io/@rekmarks/devcon-vi

**Comment by Montoya** [comment]
You can ignore 2 and 3 on this list and transcribe this one instead: 
https://github.com/ziad-saab/ethdenver-2023-metamask-snaps-workshop
