### ISSUE TITLE
Include references for contributors

### ISSUE THREAD

**Issue by vandan** [MetaMask/mm-docs-v2#66]
- [ ] [Highlight on contributors](https://docs.metamask.io/guide/contributors.html#metamask-repositories) of documentation & code
- [ ] Guidelines and links for contributors

**Comment by alexandratran** [comment]
I'm unsure if the contributor highlight is necessary to have in the dev docs. There's not a clear section to place this info.
Also, what do you mean by "guidelines and links for contributors" outside of the readme contribution guidelines?

**Comment by vandan** [comment]
I'm starting to think we may need to add a footer kind of like what Quorum is using: https://docs.goquorum.consensys.net/

A link off of a footer might be a better place for things like the highlight on contributors.

What I mean by "links for contributors" is a link off of docs.metamask.io that visitors can find and navigate to in case they're interested in contributing.
