### ISSUE TITLE
Add Plausible analytics for parity with legacy site

### ISSUE THREAD

**Issue by vandan** [MetaMask/mm-docs-v2#71]
Need to include Plausible analytics (same as legacy site). We will eventually remove Plausible once we're comfortable with the information coming through Segment.

https://plausible.io/docs/plausible-script

**Comment by vandan** [comment]
Looks like you may have implemented Plausible in the original site @Bboyakers. Is there any chance you could take a look at this one?

**Comment by BboyAkers** [comment]
> Looks like you may have implemented Plausible in the original site @Bboyakers. Is there any chance you could take a look at this one? 

Most definitely!

**Comment by vandan** [comment]
Oh, it looks like this is done via an existing plugin @BboyAkers :
https://plausible.io/docs/docusaurus-integration

**Comment by vandan** [comment]
Went ahead with this one since we're working on a timeline to get the new site launched @BboyAkers 
There are still PRs that could use reviews though.

**Comment by BboyAkers** [comment]
Kk! Sorry for the delay on my end! I'll checkout the PRs!
