### ISSUE TITLE
Improve and consolidate navigation

### ISSUE THREAD

**Issue by eriknson** [MetaMask/mm-docs-v2#74]
The current nav setup displays different left-side navigations depending on if you're on the _Wallet_ or _Snaps_ tab by the top. I think this differentiation and having the navigation change depending on what part of our offering you're looking into can be confusing.

I suggest we integrate our nav into one overviewing all of our products, see attached draft.

<img width="1080" alt="Suggested" src="https://user-images.githubusercontent.com/34306844/227554914-cee7b1dc-fd8b-40ab-9fd9-0ec0b97f5f92.png">

**Current design for comparison**

<img width="1080" alt="Current" src="https://user-images.githubusercontent.com/34306844/227555603-5fb82301-8a12-433e-8694-79bd7e48a304.png">

**Comment by alexandratran** [comment]
Regarding the wordmark, we'd need a version of it compatible with dark mode. Do you know if one exists?

**Comment by eriknson** [comment]
Here's the [vectorized wordmark](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=14191%3A39420&t=r6WoxfwJzaMDHcNw-1). For dark mode it's the same but with white text instead of black (which I think is best to switch via code using the SVG).

Re: Documentation-specific wordmark, I think best practice would be to just add `| Documentation` in the DOM behind it instead of a custom SVG image including the text. This way it'll also adapt to light / dark mode like everything else.
